name: streamlit-yolov5
dependencies:
  - python=3.8
  - pip=21.1.3
  - pip:
    - git+https://github.com/JustAnotherArchivist/snscrape.git
    - matplotlib>=3.2.2
    - numpy>=1.18.5
    - opencv-python>=4.1.2
    - Pillow
    - PyYAML>=5.3.1
    - scipy>=1.4.1
    - torch==1.8.0+cu111
    - torchvision==0.9.0+cu111
    - tqdm>=4.41.0
    - tensorboard>=2.4.1
    - seaborn>=0.11.0
    - pandas
    - thop
    - --find-links https://download.pytorch.org/whl/torch_stable.html


